### PR TITLE
chore(husky): fix husky v7 hooks

### PR DESCRIPTION
**Pull request by chimurai**
👋 😀   @onderceylan 

This fixes husky v7 hooks (husky configuration was in v4 style)

### CODE REVIEW

**Comment by onderceylan** [comment]
Hey @chimurai, it's great to hear from you! 👋 😀  And, thanks a lot for the fix! I will merge it asap.

**Review by onderceylan — DISMISSED** [review]

**Comment by onderceylan** [comment]
@chimurai can you please rebase master into your branch so we can directly merge this PR?

**Comment by chimurai** [comment]
Rebased with master. 👍

**Review by onderceylan — APPROVED** [review]

**Pull request merged**
