### PR TITLE
Allow path override of empty string

### PR DESCRIPTION
**Pull request by willheslam**
Allows for paths in the root of the domain
e.g. in a next.js app where the output file path may be /public/foo.png
but the URL would be /foo.png

Please let me know if there's another way to achieve this that I might be missing! :)

### CODE REVIEW

**Review by onderceylan — APPROVED** [review]

**Comment by onderceylan** [comment]
Hey @willheslam, thanks for the PR! Can you please rebase master into your branch so we can directly merge this PR?

**Comment by willheslam** [comment]
> Hey @willheslam, thanks for the PR! Can you please rebase master into your branch so we can directly merge this PR?

Done! 👍

**Comment by onderceylan** [comment]
I've just noticed that the commit message is not according to [conventional commit messages](https://www.conventionalcommits.org/en/v1.0.0/). Can you please amend your commit message to something like `fix(main): allow path override of empty string`?

This is required for [semantic versioning of the automated release](https://github.com/onderceylan/pwa-asset-generator/blob/master/CONTRIBUTING.md#commit-messages-and-continuous-deployment) that will be triggered when this PR is merged.

Rebasing master is also needed to merge it directly after. Thanks for your help!

**Comment by willheslam** [comment]
Apologies - my fault for not properly reading the contributing docs! I've amended the commit now.

**Review by onderceylan — APPROVED** [review]

**Comment by onderceylan** [comment]
> Apologies - my fault for not properly reading the contributing docs! I've amended the commit now.

No worries at all! Thanks a lot for your contribution 🙏🏼

**Pull request merged**
