### PR TITLE
Avoid timing out when generating images

### PR DESCRIPTION
**Pull request by guidupuy**

### CODE REVIEW

**Comment by onderceylan** [comment]
Hey @guidupuy, thanks for the PR. Can you please elaborate the issue you were facing?

**Comment by guidupuy** [comment]
The default 30s timeout was getting reached, causing the process to exit with an error.

**Comment by onderceylan** [comment]
I understand, thanks for the explanation. 

Sorry that the contribution guidelines are not published yet and the details are not clear on how to approach to a PR. The project uses semantic-release and commitizen pair for continuous deployment. There must be an active issue, and via commitizen a commit must be tagged with `fix` prefix pointing out the issue nr. When it's merged to master, it will automatically deploy a release based on commit messages.

I think we have 2 options here.

* You can either create a new PR with correct commit message pointing out a to be created issue as described above
* I reject this PR and do the described myself

What do you prefer?

**Comment by guidupuy** [comment]
It’s perfectly fine if you do it yourself!

**Comment by onderceylan** [comment]
Ok, I will do that. Sorry for the uncertainty on the contribution. It will be clear soon how to contribute with the contribution guidelines in place. And, your contribution is more than welcome!

**Comment by onderceylan** [comment]
I created an issue and will merge the fix asap: https://github.com/onderceylan/pwa-asset-generator/issues/28

**Pull request closed without merging**
